/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BusinessContainer: typeof import('./src/components/left-comp/business-container/index.vue')['default']
    DraggableTransition: typeof import('./src/components/common/draggable-transition/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HeaderButtonArea: typeof import('./src/components/header-button-area/index.vue')['default']
    IconExport: typeof import('./src/components/icons/IconExport.vue')['default']
    IconGithub: typeof import('./src/components/icons/IconGithub.vue')['default']
    IconMason: typeof import('./src/components/icons/IconMason.vue')['default']
    IconNext: typeof import('./src/components/icons/IconNext.vue')['default']
    IconReturn: typeof import('./src/components/icons/IconReturn.vue')['default']
    IconRun: typeof import('./src/components/icons/IconRun.vue')['default']
    IconTheme: typeof import('./src/components/icons/IconTheme.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
