name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. 安装 pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: latest         # 或指定 9 / latest

      # 2. 安装 Node（pnpm 缓存自动生效）
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # 3. 安装依赖 & 构建
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build

      # 4. 上传产物
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist        # 按实际产物目录改

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
